theme: jekyll-theme-time-machine
title: Welcome to Lynnae's homepage!
description: Use your imaginationnnn

<h3> Previous Artwork</h3>
<p>
<a href="images/Curls.jpg"><img src="images/Curls.jpg"></a>
</p>
