theme: jekyll-theme-time-machine
title: Welcome to Lynnae's homepage!
description: Use your imaginationnnn

<h3> Previous Artwork</h3>
<p>
<a href="p1.html"><img src="Curls.jpg" alt="Photo 1"></a>
</p>
