theme: jekyll-theme-time-machine
title: Welcome to Lynnae's homepage!
description: Use your imaginationnnn

<h3> Previous Artwork</h3>
<p>
<a href="images/Curls.jpg"><img src="images/Curls.jpg"></a>
</p>




**Test for Picture hover and color changes*
body{
	font-family: sans serif;
}
h1{
	text-align: center;
	margin: 30px 0 50px;
}

.gallery{
	margin: 10px 50px;
}
.gallery img{
	width: 230px;
	padding:5px;
	filter: grayscale(100%);
	transition: 1s:
}
.gallery img:hover{
	filter:greyscale(0);
	transform:scale(1.1);
}
